/**
 * Created by exile on 11/01/14.
 */
const eventDescriptions = {
    // Based on October 2012 specification
    100: {summaryTxt: "Medical", alarmType: "Zone", descTxt: "A non-specific medical condition exists"},
    101: {summaryTxt: "Personal Emergency", alarmType: "Zone", descTxt: "Emergency Assistance request"},
    102: {summaryTxt: "Fail to report in", alarmType: "Zone", descTxt: "A user has failed to activate a monitoring device"},
    110: {summaryTxt: "Fire", alarmType: "Zone", descTxt: "A non-specific fire alarm condition exists"},
    111: {summaryTxt: "Smoke", alarmType: "Zone", descTxt: "An alarm has been triggered by a smoke detector"},
    112: {summaryTxt: "Combustion", alarmType: "Zone", descTxt: "An alarm has been triggered by a combustion detector"},
    113: {summaryTxt: "Water Flow", alarmType: "Zone", descTxt: "An alarm has been triggered by a water flow detector"},
    114: {summaryTxt: "Heat", alarmType: "Zone", descTxt: "An alarm has been triggered by a heat detector"},
    115: {summaryTxt: "Pull Station", alarmType: "Zone", descTxt: "A pull station has been activated"},
    116: {summaryTxt: "Duct", alarmType: "Zone", descTxt: "An alarm has been triggered by a duct detector"},
    117: {summaryTxt: "Flame", alarmType: "Zone", descTxt: "An alarm has been triggered by a flame detector"},
    118: {summaryTxt: "Near Alarm", alarmType: "Zone", descTxt: "A near-alarm condition has been detected on a fire sensor"},
    120: {summaryTxt: "Panic", alarmType: "Zone", descTxt: "A non-specific hold-up alarm exists"},
    121: {summaryTxt: "Duress", alarmType: "User", descTxt: "A duress code has been entered by a user"},
    122: {summaryTxt: "Silent", alarmType: "Zone", descTxt: "A silent hold-up alarm exists"},
    123: {summaryTxt: "Audible", alarmType: "Zone", descTxt: "An audible hold-up alarm exists"},
    124: {summaryTxt: "Duress – Access granted", alarmType: "Zone", descTxt: "A duress code has been entered and granted at an entry door"},
    125: {summaryTxt: "Duress – Egress granted", alarmType: "Zone", descTxt: "A duress code has been entered and granted at an exit door"},
    126: {summaryTxt: "Hold-up suspicion print", alarmType: "User", descTxt: "A user has activated a trigger to indicate a suspicious condition"},
    130: {summaryTxt: "Burglary", alarmType: "Zone", descTxt: "A burglary zone has been violated while armed"},
    131: {summaryTxt: "Perimeter", alarmType: "Zone", descTxt: "A perimeter zone has been violated while armed"},
    132: {summaryTxt: "Interior", alarmType: "Zone", descTxt: "An interior zone has been violated while armed"},
    133: {summaryTxt: "24 Hour (Safe)", alarmType: "Zone", descTxt: "A 24 hour burglary zone has been violated"},
    134: {summaryTxt: "Entry/Exit", alarmType: "Zone", descTxt: "An Entry/Exit zone has been violated while armed"},
    135: {summaryTxt: "Day/Night", alarmType: "Zone", descTxt: "An trouble by Day / alarm by Night zone has been violated while armed"},
    136: {summaryTxt: "Outdoor", alarmType: "Zone", descTxt: "An outdoor burglary zone has been violated while armed"},
    137: {summaryTxt: "Tamper", alarmType: "Zone", descTxt: "A burglary zone has been tampered with while armed"},
    138: {summaryTxt: "Near alarm", alarmType: "Zone", descTxt: "A burg sensor has detected a condition which will cause it to go into alarm if the condition worsens"},
    139: {summaryTxt: "Intrusion Verifier", alarmType: "Zone", descTxt: "The specified zone has verified that an intrusion has occurred"},
    140: {summaryTxt: "General Alarm", alarmType: "Zone", descTxt: "The specified zone is in an alarm condition"},
    141: {summaryTxt: "Polling loop open", alarmType: "Zone", descTxt: "An open circuit condition has been detected on a polling loop while the system was armed"},
    142: {summaryTxt: "Polling loop short", alarmType: "Zone", descTxt: "A short circuit condition has been detected on a polling loop while the system was armed"},
    143: {summaryTxt: "Expansion module failure", alarmType: "Zone", descTxt: "A general failure condition has been detected on an expansion module while the system was armed"},
    144: {summaryTxt: "Sensor tamper", alarmType: "Zone", descTxt: "A sensor's tamper has been violated (case opened)"},
    145: {summaryTxt: "Expansion module tamper", alarmType: "Zone", descTxt: "An expansion module's tamper has been violated (cabinet opened)"},
    146: {summaryTxt: "Silent Burglary", alarmType: "Zone", descTxt: "A burglary zone has been violated while armed with no audible notification produced"},
    147: {summaryTxt: "Sensor Supervision Failure", alarmType: "Zone", descTxt: "A sensor's supervisory circuit has reported a failure while the system was armed"},
    150: {summaryTxt: "24 Hour Non-Burglary", alarmType: "Zone", descTxt: "A non-burglary zone has been faulted"},
    151: {summaryTxt: "Gas detected", alarmType: "Zone", descTxt: "The gas detector assigned to the specified zone has reported a fault condition"},
    152: {summaryTxt: "Refrigeration", alarmType: "Zone", descTxt: "The refrigeration detector assigned to the specified zone has reported a fault condition"},
    153: {summaryTxt: "Loss of heat", alarmType: "Zone", descTxt: "The temperature detector assigned to the specified zone has reported a fault condition"},
    154: {summaryTxt: "Water Leakage", alarmType: "Zone", descTxt: "The water leak detector assigned to the specified zone has reported a fault condition"},
    155: {summaryTxt: "Foil Break", alarmType: "Zone", descTxt: "The specified zone which is assigned to foil used as glass break detection has reported a fault condition"},
    156: {summaryTxt: "Day Trouble", alarmType: "Zone", descTxt: "The specified zone which monitors trouble by day has reported a fault condition while disarmed"},
    157: {summaryTxt: "Low bottled gas level", alarmType: "Zone", descTxt: "The gas level detector assigned to the specified zone has reported a fault condition"},
    158: {summaryTxt: "High temp", alarmType: "Zone", descTxt: "The over-temperature detector assigned to the specified zone has reported a fault condition"},
    159: {summaryTxt: "Low temp", alarmType: "Zone", descTxt: "The under-temperature detector assigned to the specified zone has reported a fault condition"},
    161: {summaryTxt: "Loss of air flow", alarmType: "Zone", descTxt: "The air flow detector assigned to the specified zone has reported a fault condition"},
    162: {summaryTxt: "Carbon Monoxide detected", alarmType: "Zone", descTxt: "The carbon monoxide detector assigned to the specified zone has reported a fault condition"},
    163: {summaryTxt: "Tank level", alarmType: "Zone", descTxt: "The tank level detector assigned to the specified zone has reported a fault condition"},
    168: {summaryTxt: "High Humidity", alarmType: "Zone", descTxt: "A High Humidity condition has been detected"},
    169: {summaryTxt: "Low Humidity", alarmType: "Zone", descTxt: "A Low Humidity condition has been detected"},
    200: {summaryTxt: "Fire Supervisory", alarmType: "Zone", descTxt: "The supervisory circuit of the specified fire zone has reported a fault condition"},
    201: {summaryTxt: "Low water pressure", alarmType: "Zone", descTxt: "The water pressure sensor assigned to the specified zone has reported a fault condition"},
    202: {summaryTxt: "Low CO2", alarmType: "Zone", descTxt: "The CO2 pressure sensor assigned to the specified zone has reported a fault condition"},
    203: {summaryTxt: "Gate valve sensor", alarmType: "Zone", descTxt: "The gate valve sensor in the fire sprinkler system assigned to the specified zone has reported a fault condition"},
    204: {summaryTxt: "Low water level", alarmType: "Zone", descTxt: "The water level sensor assigned to the specified zone has reported a fault condition"},
    205: {summaryTxt: "Pump activated", alarmType: "Zone", descTxt: "The pump activity detector assigned to the specified zone has reported an active condition"},
    206: {summaryTxt: "Pump failure", alarmType: "Zone", descTxt: "A pump output monitor assigned to the specified zone has reported a fault condition"},
    300: {summaryTxt: "System Trouble", alarmType: "Zone", descTxt: "A general system trouble condition has been reported by the specified zone"},
    301: {summaryTxt: "AC Loss", alarmType: "Zone", descTxt: "AC power loss has been detected at a control or expansion module while the system was disarmed"},
    302: {summaryTxt: "Low system battery", alarmType: "Zone", descTxt: "A battery has failed a load test while the system was disarmed"},
    303: {summaryTxt: "RAM Checksum bad", alarmType: "Zone", descTxt: "A test of the system's memory has failed"},
    304: {summaryTxt: "ROM checksum bad", alarmType: "Zone", descTxt: "A test of the system's executable memory has failed"},
    305: {summaryTxt: "System reset", alarmType: "Zone", descTxt: "The system has reset and restarted"},
    306: {summaryTxt: "Panel programming changed", alarmType: "Zone", descTxt: "The programmed configuration of the panel has changed"},
    307: {summaryTxt: "Self-test failure", alarmType: "Zone", descTxt: "The system has failed a self-test"},
    308: {summaryTxt: "System shutdown", alarmType: "Zone", descTxt: "The system has been shut down and has stopped functioning"},
    309: {summaryTxt: "Battery test failure", alarmType: "Zone", descTxt: "The system backup battery has failed a load test while the system was disarmed"},
    310: {summaryTxt: "Ground fault", alarmType: "Zone", descTxt: "The panel has detected a ground fault condition"},
    311: {summaryTxt: "Battery Missing/Dead", alarmType: "Zone", descTxt: "The system has detected that the backup battery is either missing or completely discharged."},
    312: {summaryTxt: "Power Supply Overcurrent", alarmType: "Zone", descTxt: "The system power supply has reported an excessive current draw condition"},
    313: {summaryTxt: "Engineer Reset", alarmType: "User", descTxt: "The specified service person has issued a system reset"},
    314: {summaryTxt: "Primary Power Supply Failure", alarmType: "Zone", descTxt: "The system's primary power supply has failed a supervision test. Radio devices indicate this when the backup battery charging circuit has failed its supervision test"},
    316: {summaryTxt: "System Tamper", alarmType: "Zone", descTxt: "APL- System may have been tampered or compromised"},
    320: {summaryTxt: "Sounder/Relay", alarmType: "Zone", descTxt: "A trouble condition exists in the system's sounder/relay circuit"},
    321: {summaryTxt: "Bell 1", alarmType: "Zone", descTxt: "A trouble condition exists in the primary bell circuit"},
    322: {summaryTxt: "Bell 2", alarmType: "Zone", descTxt: "A trouble condition exists in the secondary bell circuit"},
    323: {summaryTxt: "Alarm relay", alarmType: "Zone", descTxt: "A trouble condition exists in the system's alarm relay circuit"},
    324: {summaryTxt: "Trouble relay", alarmType: "Zone", descTxt: "A trouble condition exists in the system's trouble relay circuit"},
    325: {summaryTxt: "Reversing relay", alarmType: "Zone", descTxt: "The specified TELCO reversing relay has reported a trouble condition"},
    326: {summaryTxt: "Notification Appliance Ckt. # 3", alarmType: "Zone", descTxt: "A trouble condition exists in the bell #3 circuit"},
    327: {summaryTxt: "Notification Appliance Ckt. #4", alarmType: "Zone", descTxt: "A trouble condition exists in the bell #4 circuit"},
    330: {summaryTxt: "System Peripheral trouble", alarmType: "Zone", descTxt: "A system peripheral device has reported a trouble condition"},
    331: {summaryTxt: "Polling loop open", alarmType: "Zone", descTxt: "An open circuit condition has been detected on a polling loop while the system was disarmed"},
    332: {summaryTxt: "Polling loop short", alarmType: "Zone", descTxt: "A short circuit condition has been detected on a polling loop while the system was disarmed"},
    333: {summaryTxt: "Expansion module failure", alarmType: "Zone", descTxt: "A general failure condition has been detected on an expansion module while the system was disarmed"},
    334: {summaryTxt: "Repeater failure", alarmType: "Zone", descTxt: "A repeater in the system has reported a failure condition while the system was disarmed"},
    335: {summaryTxt: "Local printer out of paper", alarmType: "Zone", descTxt: "The printer attached to the panel has reported an Out Of Paper condition"},
    336: {summaryTxt: "Local printer failure", alarmType: "Zone", descTxt: "The printer attached to the panel has reported a failure condition"},
    337: {summaryTxt: "Exp. Module DC Loss", alarmType: "Zone", descTxt: "An expansion module has detected a DC power loss"},
    338: {summaryTxt: "Exp. Module Low Batt.", alarmType: "Zone", descTxt: "An expansion module has detected a low battery condition"},
    339: {summaryTxt: "Exp. Module Reset", alarmType: "Zone", descTxt: "An expansion module has reset"},
    341: {summaryTxt: "Exp. Module Tamper", alarmType: "Zone", descTxt: "An expansion module has detected its taper switch has been faulted"},
    342: {summaryTxt: "Exp. Module AC Loss", alarmType: "Zone", descTxt: "An expansion module has detected the loss of AC power"},
    343: {summaryTxt: "Exp. Module self-test fail", alarmType: "Zone", descTxt: "An expansion module has failed a self-test"},
    344: {summaryTxt: "RF Receiver Jam Detect", alarmType: "Zone", descTxt: "An RF receiver has detected the presence of a jamming signal, preventing it from receiving normal signals from the system RF devices"},
    345: {summaryTxt: "AES Encryption disabled/ enabled", alarmType: "Zone", descTxt: "E345 AES Encryption has been disabled R345 AES Encryption has been enabled"},
    350: {summaryTxt: "Communication trouble", alarmType: "Zone", descTxt: "The system has experienced difficulties communicating with the central station"},
    351: {summaryTxt: "Telco 1 fault", alarmType: "Zone", descTxt: "The system has detected a fault on the primary dial-up line"},
    352: {summaryTxt: "Telco 2 fault", alarmType: "Zone", descTxt: "The system has detected a fault on the secondary dial-up line"},
    353: {summaryTxt: "Long Range Radio xmitter fault", alarmType: "Zone", descTxt: "A fault has been detected in the long range radio subsystem"},
    354: {summaryTxt: "Failure to communicate event", alarmType: "Zone", descTxt: "The system was unable to communicate an event to the central station"},
    355: {summaryTxt: "Loss of Radio supervision", alarmType: "Zone", descTxt: "The radio has not reported in its designated supervision interval"},
    356: {summaryTxt: "Loss of central polling", alarmType: "Zone", descTxt: "The radio has detected a loss in the polling signal from it's associated receiver"},
    357: {summaryTxt: "Long Range Radio VSWR problem", alarmType: "Zone", descTxt: "The Long Range Radio has reported a transmitter/antenna problem"},
    358: {summaryTxt: "Periodic Comm Test Fail /Restore", alarmType: "Zone", descTxt: "A periodic Communication path test has failed"},
    370: {summaryTxt: "Protection loop", alarmType: "Zone", descTxt: "The specified protection loop has reported a trouble condition"},
    371: {summaryTxt: "Protection loop open", alarmType: "Zone", descTxt: "The specified protection loop has reported an open-loop trouble condition"},
    372: {summaryTxt: "Protection loop short", alarmType: "Zone", descTxt: "The specified protection loop has reported a shorted-loop trouble condition"},
    373: {summaryTxt: "Fire trouble", alarmType: "Zone", descTxt: "A fire sensor has detected a trouble condition on the specified zone while the system was disarmed"},
    374: {summaryTxt: "Exit error alarm (zone)", alarmType: "Zone", descTxt: "An exit error condition has been reported for the specified alarm zone"},
    375: {summaryTxt: "Panic zone trouble", alarmType: "Zone", descTxt: "The system has detected a trouble condition on the panic zone"},
    376: {summaryTxt: "Hold-up zone trouble", alarmType: "Zone", descTxt: "The system has detected a trouble condition on the hold-up zone"},
    377: {summaryTxt: "Swinger Trouble", alarmType: "Zone", descTxt: "A fault has occurred on a zone that has been shut down due to excessive alarms"},
    378: {summaryTxt: "Cross-zone Trouble", alarmType: "Zone", descTxt: "The specified zone in a cross-zone configuration has faulted without a fault on its corresponding cross-zone in a specific time period"},
    380: {summaryTxt: "Sensor trouble", alarmType: "Zone", descTxt: "The specified sensor has reported a trouble condition"},
    381: {summaryTxt: "Loss of supervision - RF", alarmType: "Zone", descTxt: "The specified zone has failed to report in during its designated supervision period"},
    382: {summaryTxt: "Loss of supervision - RPM", alarmType: "Zone", descTxt: "An Remote Polled Module assigned to the specified zone has failed supervision"},
    383: {summaryTxt: "Sensor tamper", alarmType: "Zone", descTxt: "The tamper switch on the specified sensor has been faulted"},
    384: {summaryTxt: "RF low battery", alarmType: "Zone", descTxt: "The specified battery powered RF zone has reported a low battery condition"},
    385: {summaryTxt: "Smoke detector Hi sensitivity", alarmType: "Zone", descTxt: "A smoke detector's sensitivity level has drifted to the upper limit"},
    386: {summaryTxt: "Smoke detector Low sensitivity", alarmType: "Zone", descTxt: "A smoke detector's sensitivity level has drifted to the lower limit"},
    387: {summaryTxt: "Intrusion detector Hi sensitivity", alarmType: "Zone", descTxt: "An intrusion detector's sensitivity level has drifted to the upper limit"},
    388: {summaryTxt: "Intrusion detector Low sensitivity", alarmType: "Zone", descTxt: "An intrusion detector's sensitivity level has drifted to the lower limit"},
    389: {summaryTxt: "Sensor self-test failure", alarmType: "Zone", descTxt: "The specified sensor has failed a self-test"},
    391: {summaryTxt: "Sensor Watch trouble", alarmType: "Zone", descTxt: "A motion sensor has not been triggered within a pre-defined time interval"},
    392: {summaryTxt: "Drift Compensation Error", alarmType: "Zone", descTxt: "A smoke detector cannot automatically adjust its sensitivity"},
    393: {summaryTxt: "Maintenance Alert", alarmType: "Zone", descTxt: "The specified zone requires maintenance"},
    394: {summaryTxt: "CO Detector needs replacement", alarmType: "Zone", descTxt: "The specified Carbon Monoxide detector has reached end-of-life"},
    400: {summaryTxt: "Open/Close", alarmType: "User", descTxt: "The specified user has disarmed/armed the system"},
    401: {summaryTxt: "O/C by user", alarmType: "User", descTxt: "The specified user has disarmed/armed the system"},
    402: {summaryTxt: "Group O/C", alarmType: "Group", descTxt: "A group of zones has been armed or disarmed"},
    403: {summaryTxt: "Automatic O/C", alarmType: "User", descTxt: "A partition has been automatically armed or disarmed"},
    404: {summaryTxt: "Late to O/C (Note: use 453 or 454 instead )", alarmType: "User", descTxt: ""},
    405: {summaryTxt: "Deferred O/C (Obsolete- do not use )", alarmType: "User", descTxt: ""},
    406: {summaryTxt: "Cancel", alarmType: "User", descTxt: "The specified user has cancelled the previously reported alarm condition"},
    407: {summaryTxt: "Remote arm/disarm", alarmType: "User", descTxt: "The specified user has armed or disarmed the system from off- premises"},
    408: {summaryTxt: "Quick arm", alarmType: "User", descTxt: "The specified user has quick-armed the system"},
    409: {summaryTxt: "Keyswitch O/C", alarmType: "User", descTxt: "The specified user has armed or disarmed the system using a keyswitch"},
    441: {summaryTxt: "Armed STAY", alarmType: "User", descTxt: "The specified user has armed the system in STAY mode"},
    442: {summaryTxt: "Keyswitch Armed STAY", alarmType: "User", descTxt: "The specified user has armed the system in STAY mode using a keyswitch"},
    443: {summaryTxt: "Armed with System Trouble Override", alarmType: "User", descTxt: "The specified user has armed the system while overriding a trouble condition"},
    450: {summaryTxt: "Exception O/C", alarmType: "User", descTxt: "The system has been armed or disarmed outside of the configured time window"},
    451: {summaryTxt: "Early O/C", alarmType: "User", descTxt: "The system has been disarmed/armed by the specified user before the configured time window has started"},
    452: {summaryTxt: "Late O/C", alarmType: "User", descTxt: "The system has been disarmed/armed by the specified user after the configured time window has ended"},
    453: {summaryTxt: "Failed to Open", alarmType: "User", descTxt: "The system has failed to have been disarmed during the designated time window"},
    454: {summaryTxt: "Failed to Close", alarmType: "User", descTxt: "The system has failed to be armed during the designated time window"},
    455: {summaryTxt: "Auto-arm Failed", alarmType: "User", descTxt: "The system has failed to automatically arm itself at the designated time"},
    456: {summaryTxt: "Partial Arm", alarmType: "User", descTxt: "The system has been only partially armed by the specified user"},
    457: {summaryTxt: "Exit Error (user)", alarmType: "User", descTxt: "The specified user has made an error exiting the premises after arming the system"},
    458: {summaryTxt: "User on Premises", alarmType: "User", descTxt: "A user has disarmed the system after an alarm has occurred"},
    459: {summaryTxt: "Recent Close", alarmType: "User", descTxt: "The system had been armed within the last xx minutes"},
    461: {summaryTxt: "Wrong Code Entry", alarmType: "Zone", descTxt: ""},
    462: {summaryTxt: "Legal Code Entry", alarmType: "User", descTxt: ""},
    463: {summaryTxt: "Re-arm after Alarm", alarmType: "User", descTxt: ""},
    464: {summaryTxt: "Auto-arm Time Extended", alarmType: "User", descTxt: "A user has successfully requested that the system delay automatically arming"},
    465: {summaryTxt: "Panic Alarm Reset", alarmType: "Zone", descTxt: "The specified panic zone has been reset"},
    466: {summaryTxt: "Service On/Off Premises", alarmType: "User", descTxt: "A service person has entered or left the premises"},
    411: {summaryTxt: "Callback request made", alarmType: "User", descTxt: "A remote site (central station) has requested the panel call it back"},
    412: {summaryTxt: "Successful download/access", alarmType: "User", descTxt: "The configuration data of the system has been successfully downloaded"},
    413: {summaryTxt: "Unsuccessful access", alarmType: "User", descTxt: "A number of failed attempts have been made to remotely access the system"},
    414: {summaryTxt: "System shutdown command received", alarmType: "User", descTxt: "A central station has sent a system shutdown command to the panel"},
    415: {summaryTxt: "Dialer shutdown command received", alarmType: "User", descTxt: "A central station has sent a dialer shutdown command to the panel"},
    416: {summaryTxt: "Successful Upload", alarmType: "Zone", descTxt: "The configuration data of the system has been successfully uploaded"},
    421: {summaryTxt: "Access denied", alarmType: "User", descTxt: "The access control system has denied access to the specified user"},
    422: {summaryTxt: "Access report by user", alarmType: "User", descTxt: ""},
    423: {summaryTxt: "Forced Access", alarmType: "Zone", descTxt: "The specified access control door has been forced open"},
    424: {summaryTxt: "Egress Denied", alarmType: "User", descTxt: "The access control system has denied egress to the specified user"},
    425: {summaryTxt: "Egress Granted", alarmType: "User", descTxt: "The access control system has granted egress for the specified user"},
    426: {summaryTxt: "Access Door propped open", alarmType: "Zone", descTxt: "The specified access control door has been held open"},
    427: {summaryTxt: "Access point Door Status Monitor trouble", alarmType: "Zone", descTxt: "The specified Access Point's Door Status Monitor has reported a trouble condition to the panel"},
    428: {summaryTxt: "Access point Request To Exit trouble", alarmType: "Zone", descTxt: "The specified Access Point's Request To Exit zone has reported a trouble condition to the panel"},
    429: {summaryTxt: "Access program mode entry", alarmType: "User", descTxt: "The access control system has been put into program mode"},
    430: {summaryTxt: "Access program mode exit", alarmType: "User", descTxt: "The access control system has exited program mode"},
    431: {summaryTxt: "Access threat level change", alarmType: "User", descTxt: "The access control system's threat level has been changed"},
    432: {summaryTxt: "Access relay/trigger fail", alarmType: "Zone", descTxt: "The specified access control output device has failed to operate properly"},
    433: {summaryTxt: "Access RTE shunt", alarmType: "Zone", descTxt: "The specified Request To Exit zone has been shunted and will no longer report activity"},
    434: {summaryTxt: "Access DSM shunt", alarmType: "Zone", descTxt: "The specified Door Status Monitor zone has been shunted and will no longer report activity"},
    435: {summaryTxt: "Second Person Access", alarmType: "User", descTxt: "A second person has accessed an access point conforming to Two- Man-Rule requirements"},
    436: {summaryTxt: "Irregular Access", alarmType: "User", descTxt: ""},
    501: {summaryTxt: "Access reader disable", alarmType: "Zone", descTxt: "The credential reader on the specified access point has been disabled"},
    520: {summaryTxt: "Sounder/Relay Disable", alarmType: "Zone", descTxt: "The specified sounder or relay has been disabled"},
    521: {summaryTxt: "Bell 1 disable", alarmType: "Zone", descTxt: "The specified output for Bell 1 has been disabled"},
    522: {summaryTxt: "Bell 2 disable", alarmType: "Zone", descTxt: "The specified output for Bell 2 has been disabled"},
    523: {summaryTxt: "Alarm relay disable", alarmType: "Zone", descTxt: "The specified alarm relay has been disabled"},
    524: {summaryTxt: "Trouble relay disable", alarmType: "Zone", descTxt: "The specified trouble relay has been disabled"},
    525: {summaryTxt: "Reversing relay disable", alarmType: "Zone", descTxt: "The specified reversing relay has been disabled"},
    526: {summaryTxt: "Notification Appliance Ckt. # 3 disable", alarmType: "Zone", descTxt: "The specified output for Bell 3 has been disabled"},
    527: {summaryTxt: "Notification Appliance Ckt. # 4 disable", alarmType: "Zone", descTxt: "The specified output for Bell 4 has been disabled"},
    531: {summaryTxt: "Module Added", alarmType: "Zone", descTxt: "The specified access control module has been added to the system"},
    532: {summaryTxt: "Module Removed", alarmType: "Zone", descTxt: "The specified access control module has been removed from the system"},
    551: {summaryTxt: "Dialer disabled", alarmType: "Zone", descTxt: "The specified dialer has been disabled"},
    552: {summaryTxt: "Radio transmitter disabled", alarmType: "Zone", descTxt: "The specified radio transmitter has been disabled"},
    553: {summaryTxt: "Remote Upload/Download disabled", alarmType: "Zone", descTxt: "Remote configuration has been enabled"},
    570: {summaryTxt: "Zone/Sensor bypass", alarmType: "Zone", descTxt: "The specified zone or sensor has been bypassed"},
    571: {summaryTxt: "Fire bypass", alarmType: "Zone", descTxt: "The specified fire zone has been bypassed"},
    572: {summaryTxt: "24 Hour zone bypass", alarmType: "Zone", descTxt: "The specified 24 hour zone has been bypassed"},
    573: {summaryTxt: "Burg. Bypass", alarmType: "Zone", descTxt: "The specified burglary zone has been bypassed"},
    574: {summaryTxt: "Group bypass", alarmType: "User", descTxt: "A group of zones has been bypassed"},
    575: {summaryTxt: "Swinger bypass", alarmType: "Zone", descTxt: "The specified zone which has reported an excessive number of faults/restores in a short period of time has been bypassed"},
    576: {summaryTxt: "Access zone shunt", alarmType: "Zone", descTxt: "The specified zone in the access control system has been shunted and will no longer report activity"},
    577: {summaryTxt: "Access point bypass", alarmType: "Zone", descTxt: "The specified access point in the access control system has been bypassed and will allow the door to open (unsecured)"},
    578: {summaryTxt: "Vault Bypass", alarmType: "Zone", descTxt: "The specified vault zone has been bypassed"},
    579: {summaryTxt: "Vent Zone Bypass", alarmType: "Zone", descTxt: "The specified vent zone has been bypassed and will no longer report any activity"},
    601: {summaryTxt: "Manual trigger test report", alarmType: "Zone", descTxt: "A test report has been triggered manually"},
    602: {summaryTxt: "Periodic test report", alarmType: "Zone", descTxt: "A periodic test report has been triggered"},
    603: {summaryTxt: "Periodic RF transmission", alarmType: "Zone", descTxt: "A periodic RF path test report has been triggered"},
    604: {summaryTxt: "Fire test", alarmType: "User", descTxt: "The specified user has initiated a test of the fire alarm zones"},
    605: {summaryTxt: "Status report to follow", alarmType: "Zone", descTxt: ""},
    606: {summaryTxt: "Listen-in to follow", alarmType: "Zone", descTxt: "The system is about to activate a 2-way audio session"},
    607: {summaryTxt: "Walk test mode", alarmType: "User", descTxt: "The specified user has placed the system into the walk-test mode for testing purposes"},
    608: {summaryTxt: "Periodic test - System Trouble Present", alarmType: "Zone", descTxt: "A periodic test has been triggered but the fire system has a trouble condition present"},
    609: {summaryTxt: "Video Xmitter active", alarmType: "Zone", descTxt: "A video look-in session is about to begin"},
    611: {summaryTxt: "Point tested OK", alarmType: "Zone", descTxt: "The specified point tested successfully"},
    612: {summaryTxt: "Point not tested", alarmType: "Zone", descTxt: "The specified point has not been tested"},
    613: {summaryTxt: "Intrusion Zone Walk Tested", alarmType: "Zone", descTxt: "The specified intrusion zone has been successfully walk-tested"},
    614: {summaryTxt: "Fire Zone Walk Tested", alarmType: "Zone", descTxt: "The specified fire zone has been successfully walk-tested"},
    615: {summaryTxt: "Panic Zone Walk Tested", alarmType: "Zone", descTxt: "The specified panic zone has been successfully walk-tested"},
    616: {summaryTxt: "Service Request", alarmType: "Zone", descTxt: "A request has been made for system servicing"},
    621: {summaryTxt: "Event Log reset", alarmType: "Zone", descTxt: "The event log has been reset and all stored events have been discarded"},
    622: {summaryTxt: "Event Log 50% full", alarmType: "Zone", descTxt: "The event log is 50% full"},
    623: {summaryTxt: "Event Log 90% full", alarmType: "Zone", descTxt: "The event log is 90% full"},
    624: {summaryTxt: "Event Log overflow", alarmType: "Zone", descTxt: "The event log has overflowed and events have been lost"},
    625: {summaryTxt: "Time/Date reset", alarmType: "User", descTxt: "The time and date have been reset to a new value by the specified user"},
    626: {summaryTxt: "Time/Date inaccurate", alarmType: "Zone", descTxt: "The system time and date is known to be in error"},
    627: {summaryTxt: "Program mode entry", alarmType: "Zone", descTxt: "The system has been placed into program mode"},
    628: {summaryTxt: "Program mode exit", alarmType: "Zone", descTxt: "The system has exited program mode"},
    629: {summaryTxt: "32 Hour Event log marker", alarmType: "Zone", descTxt: ""},
    630: {summaryTxt: "Schedule change", alarmType: "Zone", descTxt: "The specified fire/burglary schedule has been changed"},
    631: {summaryTxt: "Exception schedule change", alarmType: "Zone", descTxt: "The time schedule for event reporting by exception has been changed"},
    632: {summaryTxt: "Access schedule change", alarmType: "Zone", descTxt: "The specified access control schedule has been changed"},
    641: {summaryTxt: "Senior Watch Trouble", alarmType: "Zone", descTxt: "A person has not activated a motion sensor in a specified period"},
    642: {summaryTxt: "Latch-key Supervision", alarmType: "User", descTxt: "A child has disarmed the system (after school)"},
    651: {summaryTxt: "Reserved for Ademco Use", alarmType: "Zone", descTxt: ""},
    652: {summaryTxt: "Reserved for Ademco Use", alarmType: "User", descTxt: ""},
    653: {summaryTxt: "Reserved for Ademco Use", alarmType: "User", descTxt: ""},
    654: {summaryTxt: "System Inactivity", alarmType: "Zone", descTxt: "System has not been operated for x days"},
    655: {summaryTxt: "User Code X modified by Installer", alarmType: "User", descTxt: "The Installer has modified the specified User's code"},
    703: {summaryTxt: "Auxiliary #3", alarmType: "Zone", descTxt: ""},
    704: {summaryTxt: "Installer Test", alarmType: "Zone", descTxt: ""},
    750: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    751: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    752: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    753: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    754: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    755: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    756: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    757: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    758: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    759: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    760: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    761: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    762: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    763: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    764: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    765: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    766: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    767: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    768: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    769: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    770: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    771: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    772: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    773: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    774: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    775: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    776: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    777: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    778: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    779: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    780: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    781: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    782: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    783: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    784: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    785: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    786: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    787: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    788: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    789: {summaryTxt: "User Assigned", alarmType: "", descTxt: ""},
    796: {summaryTxt: "Unable to output signal (Derived Channel)", alarmType: "Zone", descTxt: ""},
    798: {summaryTxt: "STU Controller down (Derived Channel)", alarmType: "Zone", descTxt: ""},
    900: {summaryTxt: "Download Abort", alarmType: "Downl oader ID", descTxt: "The specified Downloader ID has aborted a download sequence in progress"},
    901: {summaryTxt: "Download Start/End", alarmType: "Downl oader ID", descTxt: "Downloader has started or ended a download sequence to the panel"},
    902: {summaryTxt: "Download Interrupted", alarmType: "Downl oader ID", descTxt: "A download sequence has been interrupted"},
    910: {summaryTxt: "Auto-close with Bypass", alarmType: "Zone", descTxt: "An auto-close sequence has been started and the specified zone has been bypassed"},
    911: {summaryTxt: "Bypass Closing", alarmType: "Zone", descTxt: ""},
    912: {summaryTxt: "Fire Alarm Silence", alarmType: "", descTxt: "The fire alarm has been silenced"},
    913: {summaryTxt: "Supervisory Point test Start/End", alarmType: "User", descTxt: "A fire supervisory device has been tested"},
    914: {summaryTxt: "Hold-up test Start/End", alarmType: "User", descTxt: "The specified user has started or ended a hold-up test"},
    915: {summaryTxt: "Burg. Test Print Start/End", alarmType: "", descTxt: "The printed progress of a burglary test has been started or ended"},
    916: {summaryTxt: "Supervisory Test Print Start/End", alarmType: "", descTxt: "The printed progress of a supervisory test has been started or ended"},
    917: {summaryTxt: "Burg. Diagnostics Start/End", alarmType: "Zone", descTxt: "A burglary system diagnostic test has been started or ended"},
    918: {summaryTxt: "Fire Diagnostics Start/End", alarmType: "Zone", descTxt: "A fire system diagnostic test has been started or ended"},
    919: {summaryTxt: "Untyped diagnostics", alarmType: "Zone", descTxt: ""},
    920: {summaryTxt: "Trouble Closing (closed with burg. during exit)", alarmType: "User", descTxt: ""},
    921: {summaryTxt: "Access Denied Code Unknown", alarmType: "User", descTxt: "Access has been denied because the system did not recognize the supplied access code as valid"},
    922: {summaryTxt: "Supervisory Point Alarm", alarmType: "Zone", descTxt: "The specified supervisory point has reported an alarm condition"},
    923: {summaryTxt: "Supervisory Point Bypass", alarmType: "Zone", descTxt: "The specified supervisory point has been bypassed"},
    924: {summaryTxt: "Supervisory Point Trouble", alarmType: "Zone", descTxt: "The specified supervisory point has reported a trouble condition"},
    925: {summaryTxt: "Hold-up Point Bypass", alarmType: "Zone", descTxt: "The specified hold-up point has been bypassed"},
    926: {summaryTxt: "AC Failure for 4 hours", alarmType: "Zone", descTxt: "There has been a loss of AC power for at least four hours"},
    927: {summaryTxt: "Output Trouble", alarmType: "Zone", descTxt: "The specified output has reported a trouble condition"},
    928: {summaryTxt: "User code for event", alarmType: "User", descTxt: "This message contains the ID of the user who triggered the previous event"},
    929: {summaryTxt: "Log-off", alarmType: "User", descTxt: "The specified user has logged-off of the system"},
    954: {summaryTxt: "CS Connection Failure", alarmType: "Zone", descTxt: "The specified CS connection has failed/restored"},
    961: {summaryTxt: "Rcvr Database Connection Fail/Restore", alarmType: "Zone", descTxt: "The connection to the receiver's database has failed/restored"},
    962: {summaryTxt: "License Expiration Notify", alarmType: "Zone", descTxt: "The product license has been terminated (7810PC)"}
};

// Constructor
function CID(rawCID) {
    /*=======================================================================================================
     The object is instantiated from Ademco Contact ID block
     Based on the SIA DC-05-1999.09 Protocol specification
     The CID consists of the following parts:
     AAAA MM Q EEE PP ZZZ
     1. Account number or Subscriber ID
     2. Message Type = 18
     3. Event Qualifier - 1 = New Event or Operning; 3 = New Restore or Closing; 6 = Previously reported condition
     4. Event Code
     5. Partition number
     6. Zone number
     =======================================================================================================*/

    // We want 15 characters no more, no less
    if(rawCID.length > 15) {
        console.log("ERROR: Invalid length of the raw contact ID code received, expected 15 but received " + rawCID.length);
        return;
    }
    if(rawCID.substring(4, 6) !="18") {
        console.log("ERROR: Invalid CID received, only accepting Message Type 18. Received: " + rawCID.substring(4, 6));
        return;
    }

    this.accountID = rawCID.substring(0, 4);
    this.eventQualifier = rawCID[6];
    this.eventCode = rawCID.substring(7, 10);
    this.partition = rawCID.substring(10, 12);
    this.zone = rawCID.substring(12, 15);


}
// class methods
CID.prototype.getEventDescription = function() {
    // Returns the object for summaryTxt, alarmType and descTxt
    return eventDescriptions[this.eventCode];
};

CID.prototype.nicePrint = function() {
    // Prints a nice output of the CID in console
    console.log("+---------+-------+--------+-------+-----------+------+");
    console.log("| Account | mType | EventQ | Event | Partition | Zone |");
    console.log("+---------+-------+--------+-------+-----------+------+");
    console.log("|   " + this.accountID + "  |   18  |    " + this.eventQualifier + "   |  " + this.eventCode + "  |       " + this.partition + "  |  " + this.zone + " |");
    console.log("+---------+-------+--------+-------+-----------+------+");
    console.log("Event summary: " + eventDescriptions[this.eventCode].summaryTxt);
    console.log("Event type: " + eventDescriptions[this.eventCode].alarmType);
    console.log("Event description: " + eventDescriptions[this.eventCode].descTxt);
};
// export the class
module.exports = CID;